[package]
name = "bevy-midi-graph"
version = "0.1.0"
edition = "2021"

[dependencies.bevy]
version = "0.17"
default-features = false
features = ["bevy_asset", "bevy_state"]

[dependencies]
midi-graph = { git = "https://github.com/shining-grimace/midi-graph.git", rev = "81c1d419bc03a1668f24e9259bee17961b857fab" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
bevy = { version = "0.17" }
avian3d = "0.4"
